import React, { useState, useMemo, useEffect } from 'react';
import { useLang } from '@/contexts/LanguageContext';
import { useTheme } from '@/contexts/ThemeContext';
import { useSubscription } from '@/contexts/SubscriptionContext';
import { base44 } from '@/api/base44Client';
import { FadeIn, StaggerContainer, StaggerItem } from '@/components/madar/Motion';
import WeeklyHealthReport from '@/components/reporting/WeeklyHealthReport';
import { Calendar, Download, Mail, AlertTriangle, FileText, Loader2, Sparkles, Info } from 'lucide-react';

// ── First Report (التقرير التأسيسي) ──
// A one-time foundational report generated by the `first-report` backend
// function. Rendered at the top of the Reports page; a previously saved copy
// is loaded on mount.
function FirstReportSection() {
  const { lang } = useLang();
  const { theme } = useTheme();
  const [report, setReport] = useState(null);
  const [alreadyGenerated, setAlreadyGenerated] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [failed, setFailed] = useState(false);

  const bgCard = theme === 'dark'
    ? 'bg-foreground/[0.03] border border-foreground/[0.06]'
    : 'bg-[#F2EFE8] border border-[#0A0B10]/10';
  const textColor = theme === 'dark' ? 'text-foreground' : 'text-[#0A0B10]';
  const textMuted = theme === 'dark' ? 'text-foreground/60' : 'text-[#0A0B10]/60';

  const fmt = (n) => (Number.isFinite(Number(n)) ? Number(n).toLocaleString('en-US') : '—');
  const sar = lang === 'ar' ? 'ر.س' : 'SAR';

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await base44.functions.invoke('first-report', { action: 'get' });
        if (!cancelled && res?.data?.report) setReport(res.data.report);
      } catch {
        /* no saved report yet — the generate button stays available */
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const generate = async () => {
    if (generating) return;
    setGenerating(true);
    setFailed(false);
    try {
      const res = await base44.functions.invoke('first-report', { action: 'generate' });
      if (!res?.data?.report) throw new Error('empty_report');
      setReport(res.data.report);
      setAlreadyGenerated(!!res.data.alreadyGenerated);
    } catch {
      setFailed(true);
    } finally {
      setGenerating(false);
    }
  };

  const portfolio = report?.portfolio || {};
  const uplift = portfolio.upliftEstimate;

  return (
    <FadeIn>
      <div className={`p-6 rounded-xl ${bgCard} space-y-5`}>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <FileText className="w-5 h-5 text-[#D95F3B]" />
            <div>
              <h2 className={`font-heading font-bold text-lg ${textColor}`}>
                {lang === 'ar' ? 'التقرير التأسيسي' : 'First Report'}
              </h2>
              <p className={`text-xs ${textMuted}`}>
                {lang === 'ar'
                  ? 'نظرة تأسيسية شاملة على محفظتك العقارية وأهم الفرص'
                  : 'A foundational overview of your portfolio and its top opportunities'}
              </p>
            </div>
          </div>
          {!report && (
            <button
              type="button" onClick={generate} disabled={generating}
              className="flex items-center justify-center gap-2 px-5 h-10 rounded-xl bg-gradient-to-r from-[#D95F3B] to-[#C8972A] text-white text-sm font-medium hover:shadow-lg hover:shadow-[#D95F3B]/30 transition-all disabled:opacity-60"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              {lang === 'ar' ? 'إنشاء التقرير التأسيسي' : 'Generate first report'}
            </button>
          )}
        </div>

        {failed && (
          <div className="flex items-start gap-2.5 p-3 rounded-xl bg-danger/10 border border-danger/25">
            <AlertTriangle className="w-4 h-4 text-danger mt-0.5 shrink-0" />
            <p className={`text-sm ${textMuted}`}>
              {lang === 'ar'
                ? 'تعذر إنشاء التقرير حاليًا — يرجى المحاولة مرة أخرى بعد قليل.'
                : 'We could not generate the report right now — please try again in a moment.'}
            </p>
          </div>
        )}

        {report && (
          <div className="space-y-5">
            {alreadyGenerated && (
              <p className={`flex items-start gap-1.5 text-xs ${textMuted}`}>
                <Info className="w-3.5 h-3.5 mt-px shrink-0" />
                {lang === 'ar'
                  ? 'تم إنشاء تقريرك التأسيسي مسبقًا — هذه نسخته المحفوظة.'
                  : 'Your first report was already generated — this is the saved copy.'}
              </p>
            )}

            {report.summary && (
              <p className={`text-sm leading-relaxed ${textColor}`}>
                {lang === 'ar' ? report.summary.ar : report.summary.en}
              </p>
            )}

            {/* Portfolio stat tiles */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="p-4 rounded-xl bg-foreground/[0.03] border border-foreground/[0.08]">
                <p className={`text-[11px] ${textMuted}`}>{lang === 'ar' ? 'عدد العقارات' : 'Properties'}</p>
                <p className={`text-lg font-bold nums ${textColor}`} dir="ltr">{fmt(portfolio.propertiesCount)}</p>
              </div>
              <div className="p-4 rounded-xl bg-foreground/[0.03] border border-foreground/[0.08]">
                <p className={`text-[11px] ${textMuted}`}>{lang === 'ar' ? 'الإيراد الشهري الإجمالي' : 'Gross monthly'}</p>
                <p className={`text-lg font-bold nums ${textColor}`} dir="ltr">{fmt(portfolio.grossMonthly)} {sar}</p>
              </div>
              <div className="p-4 rounded-xl bg-foreground/[0.03] border border-foreground/[0.08]">
                <p className={`text-[11px] ${textMuted}`}>{lang === 'ar' ? 'الصافي الشهري بعد العمولات' : 'Net monthly after fees'}</p>
                <p className={`text-lg font-bold nums ${textColor}`} dir="ltr">{fmt(portfolio.netMonthlyAfterFees)} {sar}</p>
              </div>
            </div>

            {/* Top-3 actions */}
            {(report.actions || []).length > 0 && (
              <div className="space-y-2">
                <h3 className={`text-sm font-semibold ${textColor}`}>
                  {lang === 'ar' ? 'أهم الخطوات المقترحة' : 'Top recommended actions'}
                </h3>
                {(report.actions || []).slice(0, 3).map((action, i) => (
                  <div key={i} className="flex items-start gap-3 p-4 rounded-xl bg-foreground/[0.03] border border-foreground/[0.08]">
                    <span className="w-6 h-6 rounded-full bg-[#D95F3B]/10 text-[#D95F3B] flex items-center justify-center text-xs font-bold nums shrink-0">
                      {i + 1}
                    </span>
                    <div className="space-y-1">
                      <p className={`text-sm font-semibold ${textColor}`}>
                        {lang === 'ar' ? action.title?.ar : action.title?.en}
                      </p>
                      <p className={`text-xs ${textMuted}`}>{lang === 'ar' ? action.fix?.ar : action.fix?.en}</p>
                      <p className="text-xs text-success">{lang === 'ar' ? action.benefit?.ar : action.benefit?.en}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Fee breakdown */}
            {(portfolio.feeBreakdown || []).length > 0 && (
              <div className="space-y-2">
                <h3 className={`text-sm font-semibold ${textColor}`}>
                  {lang === 'ar' ? 'تفصيل عمولات المنصات' : 'Platform fee breakdown'}
                </h3>
                <div className="overflow-x-auto rounded-xl border border-foreground/[0.08]">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className={`text-start text-xs ${textMuted} border-b border-foreground/[0.08]`}>
                        <th className="text-start font-medium px-4 py-2.5">{lang === 'ar' ? 'المنصة' : 'Platform'}</th>
                        <th className="text-start font-medium px-4 py-2.5">{lang === 'ar' ? 'العمولة' : 'Rate'}</th>
                        <th className="text-start font-medium px-4 py-2.5">{lang === 'ar' ? 'الصافي' : 'Net'}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {portfolio.feeBreakdown.map((row, i) => (
                        <tr key={i} className={i > 0 ? 'border-t border-foreground/[0.06]' : ''}>
                          <td className={`px-4 py-2.5 ${textColor}`}>{row.platform}</td>
                          <td className={`px-4 py-2.5 nums ${textColor}`} dir="ltr">
                            {fmt(Math.round(Number(row.rate) * 1000) / 10)}%
                            {row.estimated && (
                              <span className="text-[9px] font-semibold px-1.5 py-0.5 rounded-full bg-warning/15 text-warning ms-1.5">
                                {lang === 'ar' ? 'تقديري' : 'est.'}
                              </span>
                            )}
                          </td>
                          <td className={`px-4 py-2.5 nums ${textColor}`} dir="ltr">{fmt(row.net)} {sar}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Uplift estimate */}
            {uplift && (
              <div className="p-4 rounded-xl bg-gradient-to-br from-[#D95F3B]/10 to-[#C8972A]/10 border border-[#C8972A]/25">
                <p className={`text-[11px] ${textMuted}`}>{lang === 'ar' ? 'التحسن المتوقع' : 'Estimated uplift'}</p>
                <p className={`text-lg font-bold nums ${textColor}`} dir="ltr">
                  +{fmt(uplift.sarMin)}–{fmt(uplift.sarMax)} {sar}
                  <span className={`text-sm font-medium ${textMuted}`}> ({fmt(uplift.percentMin)}–{fmt(uplift.percentMax)}%)</span>
                </p>
                {uplift.note && (
                  <p className={`text-xs mt-1 ${textMuted}`}>{lang === 'ar' ? uplift.note.ar : uplift.note.en}</p>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </FadeIn>
  );
}

// Mock properties
const mockProperties = [
  { id: '1', name: 'Luxury Villa - Riyadh', city: 'Riyadh' },
  { id: '2', name: 'Modern Studio - Jeddah', city: 'Jeddah' },
  { id: '3', name: 'Beachfront Chalet - Khobar', city: 'Khobar' },
];

// Mock weekly data
const generateWeekData = (propertyId) => {
  const today = new Date();
  const weekStart = new Date(today);
  weekStart.setDate(today.getDate() - today.getDay());

  const days = [];
  for (let i = 0; i < 7; i++) {
    const date = new Date(weekStart);
    date.setDate(weekStart.getDate() + i);
    days.push({
      date: date.toISOString().split('T')[0],
      occupied: Math.random() > 0.4,
      revenue: Math.random() > 0.3 ? Math.floor(Math.random() * 1500 + 300) : 0,
    });
  }

  return {
    week: `${weekStart.toLocaleDateString()} - ${new Date(weekStart.getTime() + 6 * 24 * 60 * 60 * 1000).toLocaleDateString()}`,
    days,
  };
};

export default function Reports() {
  const { t, lang } = useLang();
  const { theme } = useTheme();
  const { entitlements, userPlan } = useSubscription();
  const [selectedPeriod, setSelectedPeriod] = useState('current');
  const [emailNotifications, setEmailNotifications] = useState(true);

  // Check feature access
  const hasAccess = useMemo(() => {
    return entitlements?.weeklyReports === true || userPlan?.slug === 'pro' || userPlan?.slug === 'growth';
  }, [entitlements, userPlan]);

  const reports = useMemo(() => {
    if (!hasAccess) return [];
    return mockProperties.map(prop => ({
      ...prop,
      weekData: generateWeekData(prop.id),
    }));
  }, [hasAccess]);

  if (!hasAccess) {
    return (
      <div className="space-y-8">
      <FirstReportSection />
      <div className={`p-8 rounded-xl text-center ${
        theme === 'dark'
          ? 'bg-foreground/[0.03] border border-foreground/[0.06]'
          : 'bg-[#F2EFE8] border border-[#0A0B10]/10'
      }`}>
        <AlertTriangle className={`w-12 h-12 mx-auto mb-4 ${
          theme === 'dark' ? 'text-[#D95F3B]' : 'text-[#D95F3B]'
        }`} />
        <h2 className={`font-heading font-bold text-lg mb-2 ${
          theme === 'dark' ? 'text-foreground' : 'text-[#0A0B10]'
        }`}>
          {lang === 'ar' ? 'ميزة غير متاحة' : 'Feature Not Available'}
        </h2>
        <p className={`text-sm ${
          theme === 'dark' ? 'text-foreground/50' : 'text-[#0A0B10]/50'
        }`}>
          {lang === 'ar'
            ? 'التقارير الأسبوعية متاحة فقط في خطط Growth و Pro'
            : 'Weekly reports are available in Growth and Pro plans'}
        </p>
      </div>
      </div>
    );
  }

  const bgCard = theme === 'dark'
    ? 'bg-foreground/[0.03] border border-foreground/[0.06]'
    : 'bg-[#F2EFE8] border border-[#0A0B10]/10';

  const textColor = theme === 'dark' ? 'text-foreground' : 'text-[#0A0B10]';
  const textMuted = theme === 'dark' ? 'text-foreground/60' : 'text-[#0A0B10]/60';

  return (
    <div className="space-y-8">
      {/* First Report (التقرير التأسيسي) */}
      <FirstReportSection />

      {/* Header */}
      <FadeIn>
        <div>
          <h1 className={`font-heading text-3xl font-bold ${textColor}`}>
            {lang === 'ar' ? 'التقارير الأسبوعية' : 'Weekly Reports'}
          </h1>
          <p className={`text-sm mt-1 ${textMuted}`}>
            {lang === 'ar'
              ? 'تقارير صحية شاملة لعقاراتك كل أسبوع'
              : 'Comprehensive health reports for your properties each week'}
          </p>
        </div>
      </FadeIn>

      {/* Controls */}
      <FadeIn delay={0.1}>
        <div className={`p-6 rounded-xl ${bgCard} flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4`}>
          <div className="flex items-center gap-4">
            <Calendar className="w-5 h-5 text-[#D95F3B]" />
            <div>
              <p className={`text-sm font-medium ${textColor}`}>
                {lang === 'ar' ? 'الفترة الزمنية' : 'Period'}
              </p>
              <div className="flex gap-2 mt-2">
                {['current', 'last4weeks', 'last3months'].map(period => (
                  <button
                    key={period}
                    onClick={() => setSelectedPeriod(period)}
                    className={`px-3 py-1.5 text-xs rounded-lg font-medium transition-all ${
                      selectedPeriod === period
                        ? 'bg-gradient-to-r from-[#D95F3B] to-[#C8972A] text-white'
                        : theme === 'dark'
                          ? 'bg-foreground/[0.04] text-foreground/70 hover:bg-foreground/[0.08]'
                          : 'bg-background/5 text-[#0A0B10]/70 hover:bg-background/10'
                    }`}
                  >
                    {period === 'current' && (lang === 'ar' ? 'الأسبوع الحالي' : 'This Week')}
                    {period === 'last4weeks' && (lang === 'ar' ? 'آخر 4 أسابيع' : 'Last 4 Weeks')}
                    {period === 'last3months' && (lang === 'ar' ? 'آخر 3 أشهر' : 'Last 3 Months')}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="flex gap-2">
            <button
              title={lang === 'ar' ? 'تحميل' : 'Download'}
              className={`p-2.5 rounded-lg transition-colors ${
                theme === 'dark'
                  ? 'hover:bg-foreground/[0.08]'
                  : 'hover:bg-background/5'
              }`}
            >
              <Download className="w-4 h-4" />
            </button>
            <label className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors cursor-pointer ${
              theme === 'dark'
                ? 'hover:bg-foreground/[0.08]'
                : 'hover:bg-background/5'
            }`}>
              <input
                type="checkbox"
                checked={emailNotifications}
                onChange={(e) => setEmailNotifications(e.target.checked)}
                className="w-4 h-4 rounded accent-[#D95F3B]"
              />
              <Mail className="w-4 h-4" />
              <span className="hidden sm:inline">
                {lang === 'ar' ? 'البريد الأسبوعي' : 'Weekly Email'}
              </span>
            </label>
          </div>
        </div>
      </FadeIn>

      {/* Reports */}
      <StaggerContainer>
        {reports.map((report, idx) => (
          <StaggerItem key={report.id}>
            <WeeklyHealthReport property={report} weekData={report.weekData} />
          </StaggerItem>
        ))}
      </StaggerContainer>

      {/* Empty State */}
      {reports.length === 0 && (
        <FadeIn>
          <div className={`p-12 rounded-xl text-center ${bgCard}`}>
            <Calendar className={`w-12 h-12 mx-auto mb-4 ${textMuted}`} />
            <p className={`text-sm ${textMuted}`}>
              {lang === 'ar' ? 'لا توجد تقارير متاحة حالياً' : 'No reports available'}
            </p>
          </div>
        </FadeIn>
      )}
    </div>
  );
}