// Draft legal content — pending review by qualified Saudi counsel.
export default {
  key: 'dataAi',
  title: { en: 'Data & AI Usage Policy', ar: 'سياسة استخدام البيانات والذكاء الاصطناعي' },
  intro: {
    en: 'This Data & AI Usage Policy governs how the Madar platform, operated by [Legal Entity Name] ("Madar", "we", "us"), uses data and artificial intelligence to provide pricing recommendations, market analytics, and assistant features to short-term-rental hosts. It explains the advisory nature of AI outputs, the limits of external market data, what information feeds our AI features, how assistant memory works, and the limitations of our liability. This Policy forms part of your agreement with Madar; by using the AI and analytics features, you accept its terms.',
    ar: 'تنظّم سياسة استخدام البيانات والذكاء الاصطناعي هذه كيفية استخدام منصة «مدار»، التي يشغّلها [اسم الكيان القانوني] («مدار»، «نحن»)، للبيانات والذكاء الاصطناعي في تقديم توصيات التسعير وتحليلات السوق وميزات المساعد لمضيفي الإيجار قصير المدة. وتوضح هذه السياسة الطبيعة الاسترشادية لمخرجات الذكاء الاصطناعي، وحدود بيانات السوق الخارجية، والمعلومات التي تُغذّي ميزات الذكاء الاصطناعي لدينا، وآلية عمل ذاكرة المساعد، وحدود مسؤوليتنا. وتُعد هذه السياسة جزءاً من اتفاقك مع «مدار»؛ وباستخدامك لميزات الذكاء الاصطناعي والتحليلات فإنك تقبل أحكامها.',
  },
  sections: [
    {
      id: 'advisory-nature',
      heading: { en: 'Advisory Nature of AI Recommendations', ar: 'الطبيعة الاسترشادية لتوصيات الذكاء الاصطناعي' },
      body: {
        en: 'All pricing recommendations, market insights, forecasts, and assistant responses generated by Madar are advisory only. They are decision-support tools intended to inform your judgment, not to replace it. You remain solely responsible for every final pricing decision, listing configuration, and business decision you take, including the consequences of adopting, adapting, or rejecting any recommendation.\n\nMadar does not provide legal, tax, accounting, investment, or regulatory advice. If a decision has legal or financial significance, you should consult a qualified professional before acting.',
        ar: 'جميع توصيات التسعير ورؤى السوق والتوقعات وردود المساعد التي تولّدها «مدار» هي توصيات استرشادية فحسب. فهي أدوات لدعم اتخاذ القرار تهدف إلى إثراء تقديرك الشخصي لا إلى الحلول محله. وتظل وحدك المسؤول عن كل قرار تسعير نهائي، وكل إعداد للإعلانات، وكل قرار تجاري تتخذه، بما في ذلك تبعات اعتماد أي توصية أو تعديلها أو رفضها.\n\nولا تقدّم «مدار» مشورة قانونية أو ضريبية أو محاسبية أو استثمارية أو تنظيمية. وإذا كان للقرار أهمية قانونية أو مالية، فينبغي لك استشارة مختص مؤهل قبل التصرف.',
      },
    },
    {
      id: 'no-guarantees',
      heading: { en: 'No Guarantees of Outcomes', ar: 'عدم ضمان النتائج' },
      body: {
        en: 'Madar makes no guarantee, representation, or warranty of any kind regarding outcomes. In particular, Madar does not guarantee revenue levels, occupancy rates, search ranking, listing visibility, approval by any listing platform, the volume or value of bookings, or that following any recommendation will result in compliance with any law, regulation, licensing requirement, or platform policy. Historical data and model outputs are not indicators of future performance, and market conditions can change rapidly and without notice.',
        ar: 'لا تقدّم «مدار» أي ضمان أو إقرار أو كفالة من أي نوع بشأن النتائج. وعلى وجه الخصوص، لا تضمن «مدار» مستويات الإيرادات، أو معدلات الإشغال، أو ترتيب الظهور في نتائج البحث، أو مدى ظهور الإعلانات، أو الحصول على موافقة أي منصة إعلانات، أو حجم الحجوزات أو قيمتها، ولا أن يؤدي اتباع أي توصية إلى الامتثال لأي نظام أو لائحة أو اشتراط ترخيص أو سياسة منصة. ولا تُعد البيانات التاريخية ومخرجات النماذج مؤشراً على الأداء المستقبلي، وقد تتغير أوضاع السوق بسرعة ودون إشعار مسبق.',
      },
    },
    {
      id: 'no-affiliation',
      heading: { en: 'No Partnership or Affiliation', ar: 'عدم وجود شراكة أو تبعية' },
      body: {
        en: 'Madar is an independent platform. Madar is not affiliated with, endorsed by, sponsored by, or partnered with Airbnb, Gathern, Booking.com, or any other listing or booking platform. References to such platforms are made solely to describe the market context in which our services operate. All trademarks, trade names, and logos of third parties remain the property of their respective owners, and their appearance in the service does not imply any relationship, approval, or association.',
        ar: '«مدار» منصة مستقلة، وهي ليست تابعة لمنصات «إير بي إن بي» أو «جاذر» أو «بوكينج دوت كوم» أو أي منصة إعلانات أو حجوزات أخرى، ولا معتمدة منها ولا مدعومة أو شريكة لها. وتقتصر الإشارات إلى تلك المنصات على وصف سياق السوق الذي تعمل فيه خدماتنا. وتظل جميع العلامات التجارية والأسماء التجارية والشعارات العائدة لأطراف ثالثة ملكاً لأصحابها، ولا يعني ظهورها في الخدمة وجود أي علاقة أو اعتماد أو ارتباط.',
      },
    },
    {
      id: 'external-data-limits',
      heading: { en: 'Limits of External Platform Data', ar: 'حدود بيانات المنصات الخارجية' },
      body: {
        en: 'Market and platform data presented in Madar may originate from public sources, third-party providers, estimates, statistical modeling, or data you import yourself. Such data may be incomplete, delayed, sampled, approximated, or otherwise inaccurate, and coverage varies by city, district, and property type. Madar does not warrant the accuracy, completeness, or timeliness of imported, scraped, or third-party data, and figures shown as estimates should be treated as such.\n\nFeatures that depend on external sources may be interrupted, degraded, or discontinued if a third-party platform changes its data availability, interfaces, or terms, or suffers an outage. Madar is not responsible for such third-party interruptions, although we will use reasonable efforts to restore affected features.',
        ar: 'قد تنشأ بيانات السوق والمنصات المعروضة في «مدار» من مصادر عامة، أو من مزوّدين خارجيين، أو من تقديرات، أو من نمذجة إحصائية، أو من بيانات تستوردها بنفسك. وقد تكون هذه البيانات غير مكتملة أو متأخرة أو معتمدة على عيّنات أو تقريبية أو غير دقيقة بأي شكل آخر، وتتفاوت التغطية بحسب المدينة والحي ونوع العقار. ولا تضمن «مدار» دقة البيانات المستوردة أو المستخلَصة أو الواردة من أطراف ثالثة ولا اكتمالها أو حداثتها، وينبغي التعامل مع الأرقام المعروضة بوصفها تقديرات على هذا الأساس.\n\nوقد تتعرض الميزات المعتمدة على مصادر خارجية للانقطاع أو التراجع أو الإيقاف إذا غيّرت منصة خارجية إتاحة بياناتها أو واجهاتها أو شروطها، أو تعرضت لعطل. ولا تتحمل «مدار» المسؤولية عن هذه الانقطاعات الناجمة عن أطراف ثالثة، وإن كنا سنبذل جهوداً معقولة لاستعادة الميزات المتأثرة.',
      },
    },
    {
      id: 'ai-errors-human-review',
      heading: { en: 'AI Errors, Hallucinations, and Human Review', ar: 'أخطاء الذكاء الاصطناعي والهلوسة والمراجعة البشرية' },
      body: {
        en: 'AI systems, including large language models, can produce outputs that are incorrect, outdated, incomplete, or fabricated ("hallucinations"), even when presented confidently. Recommendations may occasionally be unsuitable for your specific property, season, or market segment. You must review every AI output with human judgment before acting on it, and you must not treat any output as a verified fact or professional determination.\n\nAI and assistant features are subject to word, message, or usage limits according to your subscription plan. Madar may apply fair-use controls, throttling, or model changes to preserve service quality, and will describe applicable limits in the plan documentation.',
        ar: 'قد تُنتج أنظمة الذكاء الاصطناعي، بما فيها النماذج اللغوية الكبيرة، مخرجات غير صحيحة أو قديمة أو ناقصة أو مختلَقة («هلوسة»)، حتى وإن عُرضت بصياغة تُوحي بالثقة. وقد تكون بعض التوصيات أحياناً غير ملائمة لعقارك أو موسمك أو شريحة سوقك على وجه التحديد. ويجب عليك مراجعة كل مخرجات الذكاء الاصطناعي بتقدير بشري قبل التصرف بناءً عليها، وألا تتعامل مع أي مخرج بوصفه حقيقة موثَّقة أو رأياً مهنياً معتمداً.\n\nوتخضع ميزات الذكاء الاصطناعي والمساعد لحدود على عدد الكلمات أو الرسائل أو الاستخدام وفقاً لخطة اشتراكك. ويجوز لـ«مدار» تطبيق ضوابط الاستخدام العادل أو تقييد المعدل أو تغيير النماذج حفاظاً على جودة الخدمة، مع بيان الحدود السارية في وثائق الخطط.',
      },
    },
    {
      id: 'data-feeding-ai',
      heading: { en: 'What Data Feeds Our AI', ar: 'البيانات التي تُغذّي الذكاء الاصطناعي لدينا' },
      body: {
        en: 'To generate recommendations and assistant responses, Madar processes: property inputs you provide (listing details, locations, districts, amenities, base rates, and pricing settings); market metrics relevant to your properties (such as area-level demand indicators, seasonality patterns, and comparable pricing signals); and the questions and instructions you submit to the assistant. This data is processed for the sole purpose of delivering the requested feature to you, in accordance with our Privacy Policy.',
        ar: 'لتوليد التوصيات وردود المساعد، تعالج «مدار» ما يلي: مدخلات العقارات التي تقدمها (تفاصيل الإعلانات والمواقع والأحياء والمرافق والأسعار الأساسية وإعدادات التسعير)؛ ومؤشرات السوق ذات الصلة بعقاراتك (مثل مؤشرات الطلب على مستوى المنطقة وأنماط الموسمية وإشارات التسعير المقارِنة)؛ والأسئلة والتعليمات التي ترسلها إلى المساعد. وتُعالَج هذه البيانات لغرض وحيد هو تقديم الميزة المطلوبة إليك، وفقاً لسياسة الخصوصية لدينا.',
      },
    },
    {
      id: 'assistant-memory',
      heading: { en: 'Assistant Memory', ar: 'ذاكرة المساعد' },
      body: {
        en: 'On eligible subscription plans, the Madar assistant maintains a memory of context relevant to you and your properties so that conversations and recommendations become more useful over time. Assistant memory is private to your account and scoped per user and per property; it is never shared with, or visible to, other users. Memory is available only on plans that include this feature, and you may request deletion of stored memory at any time, after which it will be removed from active use in accordance with our retention practices.',
        ar: 'في خطط الاشتراك المؤهلة، يحتفظ مساعد «مدار» بذاكرة للسياق المتصل بك وبعقاراتك بحيث تصبح المحادثات والتوصيات أكثر فائدة بمرور الوقت. وذاكرة المساعد خاصة بحسابك ومقيّدة النطاق لكل مستخدم ولكل عقار؛ ولا تُشارَك مع مستخدمين آخرين ولا تكون مرئية لهم بأي حال. ولا تتاح الذاكرة إلا في الخطط التي تتضمن هذه الميزة، ويجوز لك طلب حذف الذاكرة المخزنة في أي وقت، وعندها تُزال من الاستخدام النشط وفقاً لممارسات الاحتفاظ لدينا.',
      },
    },
    {
      id: 'no-third-party-training',
      heading: { en: 'No Training of Third-Party Models on Your Content', ar: 'عدم تدريب نماذج الأطراف الثالثة على محتواك' },
      body: {
        en: 'We commit that your content — including property inputs, pricing data, and assistant conversations — is not used to train third-party foundation models beyond what is necessary to process your specific request. We select AI providers and configure our integrations so that data submitted for processing is used to generate the requested output and is not retained by the provider for its own model-training purposes. If this commitment ever changes for a specific feature, we will inform you clearly and, where required by law, obtain your consent before the change applies to your data.',
        ar: 'نلتزم بألا يُستخدم محتواك — بما في ذلك مدخلات العقارات وبيانات التسعير ومحادثات المساعد — في تدريب النماذج الأساسية التابعة لأطراف ثالثة بما يتجاوز القدر اللازم لمعالجة طلبك المحدد. ونختار مزوّدي الذكاء الاصطناعي ونهيّئ تكاملاتنا بحيث تُستخدم البيانات المرسلة للمعالجة في توليد المخرجات المطلوبة فحسب، ولا يحتفظ بها المزوّد لأغراض تدريب نماذجه الخاصة. وإذا تغيّر هذا الالتزام يوماً ما بالنسبة لميزة محددة، فسنُعلمك بذلك بوضوح، وسنحصل على موافقتك قبل سريان التغيير على بياناتك متى اقتضى النظام ذلك.',
      },
    },
    {
      id: 'liability-limitation',
      heading: { en: 'Limitation of Liability', ar: 'حدود المسؤولية' },
      body: {
        en: 'The Madar platform, including all AI features, analytics, and data, is provided "as is" and "as available", without warranties of any kind, whether express or implied, including warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement, except as cannot be excluded under applicable law.\n\nTo the maximum extent permitted by the laws of the Kingdom of Saudi Arabia, the aggregate liability of Madar and [Legal Entity Name] arising out of or in connection with the platform, whatever the basis of the claim, shall not exceed the total fees you actually paid to Madar in the twelve (12) months preceding the event giving rise to the claim. To the same extent, Madar shall not be liable for any indirect, incidental, special, or consequential damages, or for loss of profits, revenue, bookings, data, or business opportunity, even if advised of the possibility of such damages. Nothing in this section excludes liability that cannot be excluded under mandatory provisions of Saudi law.',
        ar: 'تُقدَّم منصة «مدار»، بما فيها جميع ميزات الذكاء الاصطناعي والتحليلات والبيانات، «كما هي» و«حسب توافرها»، دون أي ضمانات من أي نوع، صريحة كانت أو ضمنية، بما في ذلك ضمانات القابلية للتسويق أو الملاءمة لغرض معين أو الدقة أو عدم الانتهاك، وذلك باستثناء ما لا يجوز استبعاده بموجب الأنظمة المعمول بها.\n\nوإلى الحد الأقصى الذي تجيزه أنظمة المملكة العربية السعودية، لا تتجاوز المسؤولية الإجمالية لـ«مدار» و[اسم الكيان القانوني] الناشئة عن المنصة أو المتصلة بها، أياً كان أساس المطالبة، إجماليَّ الرسوم التي دفعتها فعلياً لـ«مدار» خلال الاثني عشر (12) شهراً السابقة للواقعة التي نشأت عنها المطالبة. وإلى الحد ذاته، لا تتحمل «مدار» المسؤولية عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية، ولا عن فوات الأرباح أو الإيرادات أو الحجوزات أو فقدان البيانات أو الفرص التجارية، حتى وإن أُخطرت باحتمال وقوع تلك الأضرار. وليس في هذا القسم ما يستبعد مسؤوليةً لا يجوز استبعادها بموجب الأحكام الآمرة في الأنظمة السعودية.',
      },
    },
    {
      id: 'changes-to-policy',
      heading: { en: 'Changes to This Policy', ar: 'التعديلات على هذه السياسة' },
      body: {
        en: 'We may update this Data & AI Usage Policy from time to time to reflect new features, changes in our AI providers or data sources, or changes in applicable law. Material changes will be announced through the platform or by email before they take effect, and the effective date will be updated accordingly. Your continued use of the AI and analytics features after the effective date constitutes acceptance of the updated Policy.',
        ar: 'يجوز لنا تحديث سياسة استخدام البيانات والذكاء الاصطناعي هذه من وقت لآخر بما يعكس الميزات الجديدة، أو التغييرات في مزوّدي الذكاء الاصطناعي أو مصادر البيانات لدينا، أو التغييرات في الأنظمة المعمول بها. وسيُعلن عن التعديلات الجوهرية عبر المنصة أو بالبريد الإلكتروني قبل سريانها، وسيُحدَّث تاريخ النفاذ تبعاً لذلك. ويُعد استمرارك في استخدام ميزات الذكاء الاصطناعي والتحليلات بعد تاريخ النفاذ قبولاً بالسياسة المحدَّثة.',
      },
    },
  ],
};
